# Generated by Django 4.0.1 on 2022-01-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('3', 'Other'), ('2', 'Male'), ('1', 'Female'), ('4', 'Prefer Not Say')], max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('image', models.ImageField(default='avatar.png', upload_to='student/')),
            ],
        ),
    ]
