# Generated by Django 4.0.2 on 2022-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('4', 'Prefer Not Say'), ('1', 'Female'), ('2', 'Male'), ('3', 'Other')], max_length=50),
        ),
    ]
