# Generated by Django 4.0.1 on 2022-01-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationship', '0002_frameworks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frameworks',
            new_name='Framework',
        ),
    ]
