# Generated by Django 4.0.1 on 2022-01-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationships', '0003_rename_framework_frameworks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frameworks',
        ),
    ]
