# Generated by Django 4.0.1 on 2022-01-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields_types', '0004_alter_stud_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='image',
        ),
        migrations.AddField(
            model_name='stud',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=50),
        ),
    ]
