# Generated by Django 4.0.1 on 2022-01-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationship', '0003_rename_frameworks_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='Founder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dj_relationship.creator'),
        ),
    ]
