# Generated by Django 4.0.1 on 2022-01-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationships', '0002_framework'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Framework',
            new_name='Frameworks',
        ),
    ]
