# Generated by Django 4.0.1 on 2022-01-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationships', '0004_delete_frameworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_relationships.language')),
            ],
        ),
    ]
