# Generated by Django 4.0.1 on 2022-01-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationships', '0005_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('frameworks', models.ManyToManyField(to='dj_relationships.Framework')),
            ],
        ),
    ]
